### ISSUE TITLE
Opam release prep

### ISSUE THREAD

**Issue by rvantonder** [comby-tools/comby#247]
Gotta get rid of the opam pin dependencies. Will try upstream some changes for future releases, otherwise we're just going to have to copy these into `comby`.

- [x] `hack_parallel`: [PR upstream](https://github.com/ocaml/opam-repository/pull/18222)
- [x] vendored. `patdiff`: try upstream https://github.com/rvantonder/patdiff/commit/190799e268b7de748f7ae91a360774b0bd5ab9d9 to patdiff [context](https://github.com/sourcegraph/sourcegraph/issues/6625)
- [x] vendored. `mparser`: [issue](https://github.com/murmour/mparser/issues/13) and [PR](https://github.com/murmour/mparser/pull/12)
- [x] vendored `camlzip`: low velocity, so don't know about getting the upstream changes in. Small though, so can keep a local copy https://github.com/rvantonder/camlzip/commits/zip64. 
- [x] arm support / parallel alternative #249
- [x] 4.12 compatibility #250

Later:

- [ ] Add `.mli` file for better library use
- [ ] split `comby-server` and `comby-interactive` into separate opam files.

**Comment by aryx** [comment]
subscribe :)

**Comment by d4hines** [comment]
Also subscribing! +1!

**Comment by rvantonder** [comment]
Alright, `comby` should be available on `opam` soon! Most platforms and targets compile on the PR in `opam-repository` https://github.com/ocaml/opam-repository/pull/18255

**Comment by rvantonder** [comment]
`comby` is now available on `opam` :-) There's still some work for me to do to make it more usable as a library (a straightforward `.mli` would be nice), and I'll try do this soon.

**Comment by aryx** [comment]
Fantastic! Yes .mli would be nice. Also, would be great if there was a way to use $XXX instead of the [:a] syntax for metavariables.

**Comment by rvantonder** [comment]
@aryx yes stay tuned :-)
